// GENERATED by tools/build-avatars.py — do not edit.
export { HAIR_BASE, HAIR_RAMPS } from './palettes';
import a_body_female_light from './body-female-light.png';
import a_body_female_amber from './body-female-amber.png';
import a_body_female_taupe from './body-female-taupe.png';
import a_body_female_bronze from './body-female-bronze.png';
import a_body_female_brown from './body-female-brown.png';
import a_body_female_black from './body-female-black.png';
import a_body_male_light from './body-male-light.png';
import a_body_male_amber from './body-male-amber.png';
import a_body_male_taupe from './body-male-taupe.png';
import a_body_male_bronze from './body-male-bronze.png';
import a_body_male_brown from './body-male-brown.png';
import a_body_male_black from './body-male-black.png';
import a_eyes_brown from './eyes-brown.png';
import a_eyes_blue from './eyes-blue.png';
import a_eyes_green from './eyes-green.png';
import a_eyes_gray from './eyes-gray.png';
import a_eyes_orange from './eyes-orange.png';
import a_eyes_purple from './eyes-purple.png';
import a_shirt_tee_female from './shirt-tee-female.png';
import a_shirt_tee_male from './shirt-tee-male.png';
import a_shirt_vneck_female from './shirt-vneck-female.png';
import a_shirt_vneck_male from './shirt-vneck-male.png';
import a_shirt_scoop_female from './shirt-scoop-female.png';
import a_shirt_scoop_male from './shirt-scoop-male.png';
import a_shirt_longsleeve_female from './shirt-longsleeve-female.png';
import a_shirt_longsleeve_male from './shirt-longsleeve-male.png';
import a_shirt_tank_female from './shirt-tank-female.png';
import a_shirt_tank_male from './shirt-tank-male.png';
import a_shirt_polo_female from './shirt-polo-female.png';
import a_shirt_polo_male from './shirt-polo-male.png';
import a_shirt_cardigan_female from './shirt-cardigan-female.png';
import a_shirt_cardigan_male from './shirt-cardigan-male.png';
import a_shirt_wrap_female from './shirt-wrap-female.png';
import a_shirt_wrap_male from './shirt-wrap-male.png';
import a_hat_crown from './hat-crown.png';
import a_hat_tophat from './hat-tophat.png';
import a_hat_tiara from './hat-tiara.png';
import a_hat_wizard from './hat-wizard.png';
import a_hat_tricorne from './hat-tricorne.png';
import a_hat_bandana from './hat-bandana.png';
import a_hat_headband from './hat-headband.png';
import a_hat_santa from './hat-santa.png';
import a_hat_bonnie from './hat-bonnie.png';
import a_hair_afro from './hair-afro.png';
import a_hair_cornrows from './hair-cornrows.png';
import a_hair_dreads from './hair-dreads.png';
import a_hair_buzz from './hair-buzz.png';
import a_hair_curly from './hair-curly.png';
import a_hair_cowlick from './hair-cowlick.png';
import a_hair_bedhead from './hair-bedhead.png';
import a_hair_messy from './hair-messy.png';
import a_hair_page from './hair-page.png';
import a_hair_parted from './hair-parted.png';
import a_hair_fade from './hair-fade.png';
import a_hair_mop from './hair-mop.png';
import a_hair_bob from './hair-bob.png';
import a_hair_lob from './hair-lob.png';
import a_hair_long from './hair-long.png';
import a_hair_straight from './hair-straight.png';
import a_hair_loose from './hair-loose.png';
import a_hair_curtains from './hair-curtains.png';
import a_hair_halfup from './hair-halfup.png';
import a_hair_bun from './hair-bun.png';
import a_hair_pigtails from './hair-pigtails.png';
import a_hair_pigtails_bangs from './hair-pigtails_bangs.png';
import a_hair_braid_back from './hair-braid-back.png';
import a_hair_braid from './hair-braid.png';
import a_hair_ponytail_back from './hair-ponytail-back.png';
import a_hair_ponytail from './hair-ponytail.png';

export const BODY_URL: Record<string, Record<string, string>> = {
    "female": {
      "light": a_body_female_light,
      "amber": a_body_female_amber,
      "taupe": a_body_female_taupe,
      "bronze": a_body_female_bronze,
      "brown": a_body_female_brown,
      "black": a_body_female_black
    },
    "male": {
      "light": a_body_male_light,
      "amber": a_body_male_amber,
      "taupe": a_body_male_taupe,
      "bronze": a_body_male_bronze,
      "brown": a_body_male_brown,
      "black": a_body_male_black
    }
  };
export const EYES_URL: Record<string, string> = {
    "brown": a_eyes_brown,
    "blue": a_eyes_blue,
    "green": a_eyes_green,
    "gray": a_eyes_gray,
    "orange": a_eyes_orange,
    "purple": a_eyes_purple
  };
export const SHIRT_URL: Record<string, Record<string, string>> = {
    "tee": {
      "female": a_shirt_tee_female,
      "male": a_shirt_tee_male
    },
    "vneck": {
      "female": a_shirt_vneck_female,
      "male": a_shirt_vneck_male
    },
    "scoop": {
      "female": a_shirt_scoop_female,
      "male": a_shirt_scoop_male
    },
    "longsleeve": {
      "female": a_shirt_longsleeve_female,
      "male": a_shirt_longsleeve_male
    },
    "tank": {
      "female": a_shirt_tank_female,
      "male": a_shirt_tank_male
    },
    "polo": {
      "female": a_shirt_polo_female,
      "male": a_shirt_polo_male
    },
    "cardigan": {
      "female": a_shirt_cardigan_female,
      "male": a_shirt_cardigan_male
    },
    "wrap": {
      "female": a_shirt_wrap_female,
      "male": a_shirt_wrap_male
    }
  };
export const HAT_URL: Record<string, string> = {
    "crown": a_hat_crown,
    "tophat": a_hat_tophat,
    "tiara": a_hat_tiara,
    "wizard": a_hat_wizard,
    "tricorne": a_hat_tricorne,
    "bandana": a_hat_bandana,
    "headband": a_hat_headband,
    "santa": a_hat_santa,
    "bonnie": a_hat_bonnie
  };
export const HAIR_URL: Record<string, { front: string; back: string | null }> = {
    "afro": {
      "back": null,
      "front": a_hair_afro
    },
    "cornrows": {
      "back": null,
      "front": a_hair_cornrows
    },
    "dreads": {
      "back": null,
      "front": a_hair_dreads
    },
    "buzz": {
      "back": null,
      "front": a_hair_buzz
    },
    "curly": {
      "back": null,
      "front": a_hair_curly
    },
    "cowlick": {
      "back": null,
      "front": a_hair_cowlick
    },
    "bedhead": {
      "back": null,
      "front": a_hair_bedhead
    },
    "messy": {
      "back": null,
      "front": a_hair_messy
    },
    "page": {
      "back": null,
      "front": a_hair_page
    },
    "parted": {
      "back": null,
      "front": a_hair_parted
    },
    "fade": {
      "back": null,
      "front": a_hair_fade
    },
    "mop": {
      "back": null,
      "front": a_hair_mop
    },
    "bob": {
      "back": null,
      "front": a_hair_bob
    },
    "lob": {
      "back": null,
      "front": a_hair_lob
    },
    "long": {
      "back": null,
      "front": a_hair_long
    },
    "straight": {
      "back": null,
      "front": a_hair_straight
    },
    "loose": {
      "back": null,
      "front": a_hair_loose
    },
    "curtains": {
      "back": null,
      "front": a_hair_curtains
    },
    "halfup": {
      "back": null,
      "front": a_hair_halfup
    },
    "bun": {
      "back": null,
      "front": a_hair_bun
    },
    "pigtails": {
      "back": null,
      "front": a_hair_pigtails
    },
    "pigtails_bangs": {
      "back": null,
      "front": a_hair_pigtails_bangs
    },
    "braid": {
      "back": a_hair_braid_back,
      "front": a_hair_braid
    },
    "ponytail": {
      "back": a_hair_ponytail_back,
      "front": a_hair_ponytail
    }
  };
