// GENERATED by tools/build-avatars.py — do not edit.
export const HAIR_BASE: readonly string[] = ["#260D14", "#6A1108", "#A42600", "#BF4000", "#E55600", "#FF8A00"];
export const HAIR_RAMPS: Record<string, readonly string[]> = {
  "black": [
    "#000000",
    "#080A0A",
    "#101414",
    "#1C2222",
    "#31313E",
    "#4A5057"
  ],
  "dark_brown": [
    "#050100",
    "#160701",
    "#290E02",
    "#421603",
    "#5F1F04",
    "#792806"
  ],
  "chestnut": [
    "#200C0D",
    "#3A130E",
    "#63200B",
    "#81310A",
    "#B6550E",
    "#D28102"
  ],
  "light_brown": [
    "#1A0E04",
    "#301B07",
    "#60350F",
    "#7D4513",
    "#AE682A",
    "#C88D58"
  ],
  "blonde": [
    "#331313",
    "#552B15",
    "#AC5D1F",
    "#E09E2B",
    "#FCCF56",
    "#FFE67D"
  ],
  "platinum": [
    "#1C0E06",
    "#7D5D5D",
    "#A87D52",
    "#C0AB81",
    "#EDDF95",
    "#F6F6F3"
  ],
  "ash": [
    "#2D061B",
    "#642442",
    "#935065",
    "#C18F8A",
    "#EDDF95",
    "#FFF1C1"
  ],
  "ginger": [
    "#300500",
    "#6A1A00",
    "#9C3B01",
    "#CC6901",
    "#FAA301",
    "#FFE01E"
  ],
  "red": [
    "#300000",
    "#870000",
    "#A40712",
    "#CB0000",
    "#E21414",
    "#F1583A"
  ],
  "raven": [
    "#010107",
    "#040B18",
    "#061421",
    "#071F2A",
    "#0D384D",
    "#1A5369"
  ],
  "pink": [
    "#330410",
    "#71043A",
    "#B60A68",
    "#E941AA",
    "#E976C4",
    "#EA95D5"
  ],
  "purple": [
    "#13112D",
    "#2B225A",
    "#402E82",
    "#7141B2",
    "#A966DD",
    "#D085ED"
  ]
};
