/**
 * @party/ui — curated party sound pack. GENERATED by
 * tools/build-sound-pack.py — do not edit by hand.
 *
 * All clips are Kenney.nl, licensed CC0 (public domain). Bundled; nothing
 * is fetched at runtime. Played through @party/ui's sound system
 * (getSounds().sample(id) / .play({ sample: id })), sharing its mute state.
 */

import s_ui_click from './ui-click.ogg';
import s_ui_select from './ui-select.ogg';
import s_ui_confirm from './ui-confirm.ogg';
import s_ui_back from './ui-back.ogg';
import s_ui_error from './ui-error.ogg';
import s_ui_toggle from './ui-toggle.ogg';
import s_ui_open from './ui-open.ogg';
import s_ui_question from './ui-question.ogg';
import s_ui_tick from './ui-tick.ogg';
import s_ui_drop from './ui-drop.ogg';
import s_ui_glass from './ui-glass.ogg';
import s_card_play from './card-play.ogg';
import s_card_deal from './card-deal.ogg';
import s_card_shuffle from './card-shuffle.ogg';
import s_card_fan from './card-fan.ogg';
import s_chip_lay from './chip-lay.ogg';
import s_chip_clash from './chip-clash.ogg';
import s_dice_throw from './dice-throw.ogg';
import s_stinger_win from './stinger-win.ogg';
import s_stinger_lose from './stinger-lose.ogg';
import s_stinger_round from './stinger-round.ogg';
import s_stinger_reveal from './stinger-reveal.ogg';
import s_stinger_zap from './stinger-zap.ogg';
import s_stinger_fanfare from './stinger-fanfare.ogg';

export const SOUND_SAMPLES = {
  'ui-click': s_ui_click,
  'ui-select': s_ui_select,
  'ui-confirm': s_ui_confirm,
  'ui-back': s_ui_back,
  'ui-error': s_ui_error,
  'ui-toggle': s_ui_toggle,
  'ui-open': s_ui_open,
  'ui-question': s_ui_question,
  'ui-tick': s_ui_tick,
  'ui-drop': s_ui_drop,
  'ui-glass': s_ui_glass,
  'card-play': s_card_play,
  'card-deal': s_card_deal,
  'card-shuffle': s_card_shuffle,
  'card-fan': s_card_fan,
  'chip-lay': s_chip_lay,
  'chip-clash': s_chip_clash,
  'dice-throw': s_dice_throw,
  'stinger-win': s_stinger_win,
  'stinger-lose': s_stinger_lose,
  'stinger-round': s_stinger_round,
  'stinger-reveal': s_stinger_reveal,
  'stinger-zap': s_stinger_zap,
  'stinger-fanfare': s_stinger_fanfare,
} as const;

export type SampleId = keyof typeof SOUND_SAMPLES;

export const SAMPLE_IDS = Object.keys(SOUND_SAMPLES) as SampleId[];
