/**
 * Customizable player avatar — a small pixel "3x4 photo" built from layered
 * LPC sprite parts (body/head/eyes/shirt/hair/hat) plus a background colour.
 *
 * Every field is a catalog id (a short string). The catalogs, the layered
 * renderer and the runtime hair-recolour live in `@party/ui` (`ui/src/avatar.ts`
 * + `ui/src/avatar-assets/`, generated by `tools/build-avatars.py`). Any unknown
 * id is clamped to a default at render time, so the server only does structural
 * validation. `shared` stays types-only.
 */
export type AvatarSpec = {
  /** Body base — `female` | `male`. */
  gender: string;
  /** Skin tone id. */
  skin: string;
  /** Hair style id (`bald` = no hair). */
  hair: string;
  /** Hair colour id. */
  hairColor: string;
  /** Eye colour id. */
  eyes: string;
  /** Shirt / top id. */
  shirt: string;
  /** Hat / headwear id (`none` = no hat). */
  hat: string;
  /** Background colour id. */
  bg: string;
};
