/**
 * @party/ui — "Gabsinto" easter-egg avatar presets. GENERATED by
 * tools/build-gabsinto.py — do not edit by hand.
 *
 * AI portrait renders of the repo owner, used locally only. Unlocked in the
 * join screen by typing the name "Gabsinto"; see isGabsintoName() in avatar.ts.
 */

import face_rei from './rei.webp';
import full_rei from './rei-full.webp';
import face_general from './general.webp';
import full_general from './general-full.webp';
import face_lorde from './lorde.webp';
import full_lorde from './lorde-full.webp';
import face_nobre from './nobre.webp';
import full_nobre from './nobre-full.webp';
import face_executivo from './executivo.webp';
import full_executivo from './executivo-full.webp';
import face_enigma from './enigma.webp';
import full_enigma from './enigma-full.webp';
import face_stand from './stand.webp';
import full_stand from './stand-full.webp';
import face_feiticeiro from './feiticeiro.webp';
import full_feiticeiro from './feiticeiro-full.webp';

export interface AvatarPreset {
  /** stable id, stored in AvatarSpec.preset */
  id: string;
  emoji: string;
  label: string;
  /** square face crop — the avatar itself */
  face: string;
  /** full portrait — the glory-moment splash */
  full: string;
}

export const AVATAR_PRESETS: readonly AvatarPreset[] = [
  { id: 'rei', emoji: '👑', label: 'O Rei', face: face_rei, full: full_rei },
  { id: 'general', emoji: '🎖', label: 'O General', face: face_general, full: full_general },
  { id: 'lorde', emoji: '🎩', label: 'O Lorde', face: face_lorde, full: full_lorde },
  { id: 'nobre', emoji: '🕯', label: 'O Nobre', face: face_nobre, full: full_nobre },
  { id: 'executivo', emoji: '💼', label: 'O Executivo', face: face_executivo, full: full_executivo },
  { id: 'enigma', emoji: '🎷', label: 'O Enigma', face: face_enigma, full: full_enigma },
  { id: 'stand', emoji: '⭐', label: 'O Stand', face: face_stand, full: full_stand },
  { id: 'feiticeiro', emoji: '👁', label: 'O Feiticeiro', face: face_feiticeiro, full: full_feiticeiro },
];

export const AVATAR_PRESET_IDS: readonly string[] = AVATAR_PRESETS.map((p) => p.id);

const BY_ID = new Map(AVATAR_PRESETS.map((p) => [p.id, p]));
export const getAvatarPreset = (id: string | undefined): AvatarPreset | undefined =>
  id ? BY_ID.get(id) : undefined;
