/**
 * Original PT-BR prompt bank for Zap!. Written for this repo — not lifted from
 * Quiplash, Jackbox, `rumpus`, or any other deck. Keep them short, open-ended and
 * safe for a living-room crowd: the funny part is whatever the players type.
 *
 * Add freely. The engine shuffles this list per match and reshuffles when it runs
 * out, so order here does not matter.
 */
export const ZAP_PROMPTS: readonly string[] = [
  'O pior nome possível para um pet',
  'Uma matéria escolar que ninguém pediu',
  'O verdadeiro motivo de o Wi-Fi ter caído',
  'Algo que você NÃO quer ouvir do piloto do avião',
  'A pior frase para começar uma entrevista de emprego',
  'Um superpoder decepcionante',
  'O nome de uma banda de forró tecnológico',
  'Algo que a sua mãe jamais mandaria no grupo da família',
  'Uma regra nova e polêmica para o futebol',
  'O pior brinde possível num casamento',
  'Uma desculpa ruim para chegar atrasado no trabalho',
  'O que os pombos estão planejando',
  'Um sabor de refrigerante que foi cancelado',
  'A pior coisa para encontrar dentro de um pão de queijo',
  'Um feriado nacional que deveria existir',
  'O slogan de uma academia que ninguém quer frequentar',
  'Algo que você diria para um alien tentando impressionar a humanidade',
  'O pior nome para um navio de cruzeiro',
  'Uma habilidade inútil para colocar no currículo',
  'O que realmente acontece quando a luz da geladeira apaga',
  'Um aplicativo que ninguém deveria ter inventado',
  'A pior surpresa de aniversário',
  'Um conselho terrível para quem vai se casar amanhã',
  'O que o seu vizinho faz às 3 da manhã',
  'Uma placa de trânsito que faltou inventar',
  'O pior tema para uma festa infantil',
  'Algo que estraga qualquer churrasco',
  'Uma frase que soa bem até você pensar dois segundos',
  'O nome de um perfume que ninguém compraria',
  'A pior maneira de terminar um namoro',
  'Um novo esporte olímpico duvidoso',
  'O que o cachorro está pensando enquanto te encara',
  'Uma pergunta perigosa para fazer no primeiro encontro',
  'O pior recheio para um bolo de casamento',
  'Uma tradição de família que precisa acabar',
  'O que estava escrito no bilhete que o professor rasgou',
  'Um motivo ridículo para chamar o síndico',
  'A pior frase para vir dentro de um biscoito da sorte',
  'Algo que você encontraria na mochila de um vilão',
  'Um nome de fantasia para o pessoal do RH',
  'O pior presente de amigo secreto de R$ 20',
  'Uma manchete de jornal que ninguém quer ler no domingo',
  'O que o motorista de app comenta assim que você fecha a porta',
  'Uma atualização de celular que ninguém aprovou',
  'A pior forma de acordar alguém',
  'Um novo imposto absurdo',
  'O que a estátua da praça faria se pudesse andar por uma hora',
  'Uma frase de para-choque de caminhão que deu errado',
  'O pior lugar para guardar as chaves de casa',
  'Algo que você diria para escapar de uma reunião',
  'Um cheiro que deveria ser proibido no transporte público',
  'O nome do próximo furacão brasileiro',
  'Uma promessa de político que daria pra cumprir de verdade',
  'O que o elevador diria se estivesse cansado',
];
